AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: SAM template for Test-Express-App

Globals:
  Function:
    Timeout: 10
    MemorySize: 128

Parameters:
  Region:
    Type: String
    Default: us-east-1

Resources:
  ExpressFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/express-app/
      Handler: main.handler
      Runtime: nodejs20.x
      Environment:
        Variables:
          SECRET_KEY: 'test-secret-key'
          DB_HOST: nex-test.cmaz4l4k9vfi.eu-central-1.rds.amazonaws.com
          DB_PORT: 3306
          DB_USER: food-options-db
          DB_PASSWORD: jQCYeCt53po9puM6HIYq
          DB_DATABASE: foodoptionstest

      Events:
        ExpressFunctionProxy:
          Type: Api
          Properties:
            ApiId: !Ref HTTPApi
            Path: "/{proxy+}"
            Method: any
        ExpressFunctionRoot:
          Type: Api
          Properties:
            ApiId: !Ref HTTPApi
            Path: "/"
            Method: any
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true
        External: ['pg-hstore']
        EntryPoints:
          - main.ts

  HTTPApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: test

Outputs:
  ExpressFunction:
    Description: "Express Lambda Function"
    Value: !GetAtt ExpressFunction.Arn

  HTTPApi:
    Description: "API Gateway endpoint URL for express function"
    Value: !Sub "https://${ExpressApi}.execute-api.${AWS::Region}.amazonaws.com/test/"

